using DynastyBeacon.Models;

public class Debtor
{
    public Guid DebtorID { get; set; }
    public int ID { get; set; } // This will be auto-generated by SQL Server
    public string AccountCode { get; set; } // This is computed by SQL Server
    public string Name { get; set; }
    public string Address { get; set; }
    public string? AlternativeAddress { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public decimal Balance { get; set; }
    public decimal SalesYearToDate { get; set; }
    public decimal CostYearToDate { get; set; }
    public string? Tier { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedOn { get; set; }
    public string? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }

    // Navigation properties
    public ICollection<DebtorTransaction> DebtorTransactions { get; set; }
    public ICollection<InvoiceHeader> Invoices { get; set; }
}